### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by ChanSek** [facebook/stetho#463] opened 2016-12-05 17:20 UTC
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:394)
       at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
       at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:378)
       at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:333)
       at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
       at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:688)
       at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by rickbrew** [comment] 2016-12-05 19:01
Dupe of #381

**Closed by rickbrew** 2016-12-05 19:01 UTC
Labels: duplicate
