### ISSUE TITLE
Android N Compatibility

### ISSUE THREAD

**Issue by hzsweers** [facebook/stetho#364] opened 2016-03-16 20:02 UTC
I get the following in chrome when I try to connect with my 6P on an N-device:

`Pending authentication: please accept debugging session on the device.`

I've enabled all permissions for the app, not sure if there's anything else I need to do. Has anyone else seen this?

**Comment by jasta** [comment] 2016-03-16 22:01
Looks like a duplicate of #316.  Should be fixed with a Chrome upgrade.

**Comment by hzsweers** [comment] 2016-03-16 22:04
I'm running v48 of chrome though, would it still be the case now?

**Comment by jasta** [comment] 2016-03-17 00:03
It's entirely possible they broke it again.  The problem happens when Chrome's native USB/ADB support takes over (no longer needs or uses adbd to be running).  Normally when this happens everything is fine as Chrome's support works properly with recent versions.  But if they break anything in their ADB implementation this will keep happening.

To troubleshoot, try making sure that adb devices / adb shell ls actually does something.  If no, close all chrome://inspect windows (or just kill Chrome to be sure) and invoke the adb commands again.  The adbd service should start up and begin working again.  Then chrome://inspect _should_ work.

**Comment by longinoa** [comment] 2016-03-17 00:37
Actually I think I saw this same thing today. adb would randomly just 
stop functioning when I had chrome://inspect open...

**Comment by hzsweers** [comment] 2016-03-18 22:06
I don't know if it's a Chrome issue per se, because it worked fine when I switched to a 5.1 genymotion emulator

**Comment by jasta** [comment] 2018-01-02 20:55
It is a chrome issue for sure.  adb overall is affected, independent of Stetho.

**Closed by jasta** 2018-01-02 20:55 UTC
Labels: duplicate
