### ISSUE TITLE
App crashes android 9

### ISSUE THREAD

**Issue by kumold** [facebook/stetho#633] opened 2019-02-05 05:15 UTC
When starting to inspect with chrome app crashes with error:

> Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

**Comment by k-misztal** [comment] 2019-02-20 14:04
Same here. In my case it happens when I try to inspect layout. When the app tries to highlight the element that is being selected (hovered) in chrome console it crashes. It makes the layout inspector useless.

**Comment by giem** [comment] 2019-02-25 00:21
I believe this is a duplicate of https://github.com/facebook/stetho/issues/607, however this still hasn't been released.

**Comment by jasta** [comment] 2019-03-18 05:37
Release is incoming now.  1.5.1 should include the fix.

**Closed by jasta** 2019-03-18 05:37 UTC
