### ISSUE TITLE
Dumpapp not connecting on some clients

### ISSUE THREAD

**Issue by Actine** [facebook/stetho#331] opened 2016-01-20 01:21 UTC
I'm having an issue with dumpapp on my laptop, while on desktop PC it works just fine. The issue is the following: when a single Stetho-enabled process is active on an emulator/device, running `py dumpapp` gets stuck at `import 'stetho_open'` until I kill the app (then dumpapp reports stream failure). If there are multiple Stetho-enabled apps active, dumpapp will offer to choose which one to use, but trying to connect to any of them will report "maybe it's closed".

In both cases, same app build was used. Both systems have the same python version (Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32). The system where it works is Windows 10 64-bit, the system where it doesn't is Windows 7 Ultimate 64-bit. Chrome dev tools work fine on both. Please ping me if you need more details.

I have zero idea why this happens and what can be done with it — tomorrow I'm presenting a talk on Stetho, and apparently will have to remote-desktop to showcase dumpapp :P

**Comment by jasta** [comment] 2016-01-20 01:32
Hmm.  I assume adb shell operates normally?  Also, what does `./scripts/dumpapp -p nonsense` do?  Does it differ from `./scripts/dumpapp -p your.actual.app`?

Finally, one last debug step to try is to run this stuff manually to sniff out where and why it's failing:

adb shell cat /proc/net/unix | grep stetho
adb forward local:9999 localabstract:stetho_someapp_devtools_remote
curl http://localhost:9999/dumpapp

That's the gist of what ./scripts/dumpapp does :)

Also, try closing Chrome and seeing if that fixes it.  Older versions of Chrome were doing funny things that interfered badly with adbd.

**Comment by jasta** [comment] 2016-01-20 01:35
Also, I love that you're presenting on Stetho :)  So great to have folks helping to spread the word!

**Comment by Actine** [comment] 2016-01-20 01:48
Did try what you said. `adb shell` operates normally. `./scripts/dumpapp -p nonsense` does the same — doesn't block but says "Failure to target process nonsense: closed (is it running?)"

I followed the steps manually, there was a stetho process. Then, calling `adb forward` failed with this:
error: cannot bind listener: unknown local portname 'local:9999'

I'm sorry, I'm switching off (actually already did), it's 4 AM here now. Thank you for your help. If you have an idea how to fix this (because I'm a total newbie at both adb and unix), please let me know so that I can try it in the morning.

**Comment by jasta** [comment] 2016-01-20 01:57
Sorry that forward command should have been:
```
adb forward tcp:9999 localabstract:stetho_foo_devtools_remote
```

I'm suspecting that the problem is that for some reason the app itself is hanging accepting the socket and that the dumpapp script and adb on your machine are working fine.  But based on your description (that another machine works fine), I don't understand how that can be.  *confused*

**Comment by Actine** [comment] 2016-01-20 02:02
Will try tomorrow. The machines differ by 5 years in age, maybe that's the reason :) (although I think I tried the same with physical Nexus 5, had the same issue).

Also, love the tool. It's a godsend. Keep up the good work! :)

**Comment by jasta** [comment] 2016-01-20 22:55
How'd the presentation go? :)

**Comment by Actine** [comment] 2016-01-20 23:50
@jasta for a live demo, it went pretty well :) I didn't have time for last minute fixes though, so just presented dumpapp over remote desktop from my home machine.

Just checked your command. It all worked; I don't have curl but I managed to get the response, and it was identical to the one on the other machine. Although in the response I see some control symbols — maybe that could be the case why cmd on windows 7 couldn't load or display it?..

**Comment by Actine** [comment] 2016-01-21 00:16
P.S. There was a question whether Stetho could also hold and tamper with network requests and not just sniff them. Also whether it was possible to adjust the views via rhino since it couldn't be done in hierarchy inspector. Also people loved the database access capability but would like it to be more user-friendly than simply viewing tables and sending queries. All seem like good ideas for improvements. Also someone wondered why three inspector tabs did nothing, 'maybe I just never tried to press the record button to collect audit/profiler data'.

**Comment by jasta** [comment] 2016-01-21 00:23
Unfortunately many of those suggestions are about improving Chrome's UI not Stetho.  We don't have any direct control over Chrome, we'd have to submit our improvements upstream to them to change database access and the like.  Re the inspector tabs that don't work, it's mostly because we just haven't gotten around to implementing them.  But there's somewhat good reason: the concepts exposed via Chrome for those other tabs are really hard to make sense of in an Android app, or impossible to collect the data from where Stetho sits (inside the app, not inside the system).

Tricky problems, basically :)

**Comment by Actine** [comment] 2016-01-21 16:09
Yep, that's what I also said (although I saw some discussion about heap dumps). Also do I remember correctly that you still plan to add the possibility to edit views' attributes in Elements tab? Because despite Instant Run being announced, ability to modify colors/margins/padding, simulate pressed/enabled/disabled state etc on the go like with web pages would be tremendously helpful (btw I noticed that one can change text in TextViews already).

As for Chrome's UI, there is a possibility to make devtools extensions (e.g. extra tabs, like Polymer, Angular and React have). Maybe there's already a better Web SQL inspector out there (or maybe if I have time and I'm bored enough, I'll try to code something up).

**Comment by jasta** [comment] 2016-01-21 16:20
Yes we still plan to edit views' attributes and even edit the XML layouts directly, possibly being able to inflate new views and all that.  We just haven't really staffed adding the features yet (patches welcome *grin*).

As for devtools extensions, unfortunately, I believe how this is coded it requires that the extra tabs be part of native Chrome inspection, not Chrome remote inspection (that is inspecting an Android device).  I did see that very recently changes to Chrome may have made this possible however so it is worth a renewed look soon.

**Comment by jasta** [comment] 2016-01-21 16:20
Oops, didn't mean to hit close :)

**Comment by Actine** [comment] 2016-01-26 12:18
Well, no need to keep it open unless someone runs into the same issue. On my primary machine it works fine, and I only need my laptop once in a while, so it's unlikely that I'll look into this further from my side.

**Comment by jasta** [comment] 2016-03-02 18:24
Closing as there's nothing left actionable on this task directly.  I believe the issue you faced was due to the change in protocol with 1.3.0, that should just correct itself over time as folks upgrade their scripts and apps.

**Closed** 2016-03-02 18:23 UTC
Labels: question
