### ISSUE TITLE
Crash when inspecting a ListPreference/MultiSelectListPreference

### ISSUE THREAD

**Issue by afollestad** [facebook/stetho#618] opened 2018-09-18 04:16 UTC
While using Stetho in the sample project of one of my open source libraries, I noticed a crash.

The crash:

```groovy
Process: com.afollestad.aestheticsample, PID: 8673
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.facebook.stetho.inspector.elements.android.ViewHighlightOverlays$ViewHighlightOverlaysJellybeanMR2$MainHighlightDrawable.draw(ViewHighlightOverlays.java:141)
        at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:256)
```

This is the visual layout:

<img src="https://user-images.githubusercontent.com/1820165/45664030-97e94580-babe-11e8-9ad7-bd88f2e22b82.png" width="200" />

I get a crash when inspecting a `MultiSelectListPreference`, I'm using an AndroidX [PreferenceFragmentCompat](https://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat), not sure if it would happen in the legacy Support Library's as well.

---

I've made the contents below expandable so it's not overwhelming to look at, at first glance.

The preferences XML:

<details>

```xml
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:title="My Preferences">

  <Preference
      android:key="basic_preference"
      android:summary="Hello world, testing 1 2 1 2"
      android:title="Basic Preference"
      />

  <PreferenceCategory
      android:title="Category One">

    <CheckBoxPreference
        android:key="checkbox_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="CheckBox Preference"
        />

    <SwitchPreference
        android:key="switch_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="Switch Preference"
        />

  </PreferenceCategory>

  <PreferenceCategory
      android:title="Category Two">

    <DropDownPreference
        android:entries="@array/entries"
        android:entryValues="@array/entry_values"
        android:key="dropdown_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="Dropdown Preference"
        />

    <SeekBarPreference
        android:defaultValue="5"
        android:key="seekbar_preference"
        android:max="10"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="SeekBar Preference"
        />

  </PreferenceCategory>

  <PreferenceCategory
      android:title="Category Three">

    <EditTextPreference
        android:dialogTitle="EditText Dialog"
        android:key="edittext_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="EditText Preference"/>

    <ListPreference
        android:dialogTitle="List Dialog"
        android:entries="@array/entries"
        android:entryValues="@array/entry_values"
        android:key="list_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="List Preference"/>

    <MultiSelectListPreference
        android:dialogTitle="Multi-select List Dialog"
        android:entries="@array/entries"
        android:entryValues="@array/entry_values"
        android:key="multi_select_list_preference"
        android:summary="Hello world, testing 1 2 1 2"
        android:title="Mutli-Select Preference"/>

  </PreferenceCategory>

</PreferenceScreen>
```

</details>

---

The code that uses the preferences XML:

<details>

```kotlin
import android.os.Bundle
import androidx.preference.PreferenceFragmentCompat
import com.afollestad.aesthetic.AestheticActivity

class SettingsFragment : PreferenceFragmentCompat() {

  override fun onCreatePreferences(
    savedInstanceState: Bundle?,
    rootKey: String?
  ) = setPreferencesFromResource(R.xml.preferences, rootKey)
}

class SettingsActivity : AestheticActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_settings)

    if (savedInstanceState == null) {
      supportFragmentManager
          .beginTransaction()
          .add(R.id.container, SettingsFragment())
          .commit()
    }
  }
}
```

</details>

**Comment by jasta** [comment] 2019-03-18 06:42
Duplicate of #607.  Fixed in v1.5.1 which just released.

**Closed by jasta** 2019-03-18 06:42 UTC
