### ISSUE TITLE
Crashing !!!

### ISSUE THREAD

**Issue by pollux-** [facebook/stetho#443] opened 2016-09-29 11:17 UTC
09-29 16:46:25.638 27959 27959 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:394)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:378)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:333)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:688)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:46:25.638 27959 27959 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Kaustubh-Deshmukh** [comment] 2016-10-04 12:25
I am getting 

`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229) 
`
for version 1.4.1

**Comment by rickbrew** [comment] 2016-11-16 19:45
Duplicate of #381

**Closed by rickbrew** 2016-11-16 19:45 UTC
Labels: duplicate
