### ISSUE TITLE
Slow operation on the main thread

### ISSUE THREAD

**Issue by droidpl** [facebook/stetho#379] opened 2016-05-02 09:10 UTC
When loading stetho with the config provided I am getting with strict mode an alert:

Configuration:

```
Stetho.initialize(Stetho.newInitializerBuilder(this)
                .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
                .build());

```

Strict mode config:

```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
					.detectAll()
					.penaltyLog()
					.build());
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
					.detectLeakedSqlLiteObjects()
					.detectLeakedClosableObjects()
					.penaltyLog()
					.build());
```

Alert:

```
StrictMode policy violation; ~duration=11 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                                                                                at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1151)
                                                                                at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:132)
                                                                                at libcore.io.IoBridge.open(IoBridge.java:445)
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                                at com.facebook.stetho.common.ProcessUtil.readProcessName(ProcessUtil.java:49)
                                                                                at com.facebook.stetho.common.ProcessUtil.getProcessName(ProcessUtil.java:38)
                                                                                at com.facebook.stetho.server.AddressNameHelper.createCustomAddress(AddressNameHelper.java:20)
                                                                                at com.facebook.stetho.Stetho$Initializer.start(Stetho.java:394)
                                                                                at com.facebook.stetho.Stetho.initialize(Stetho.java:128)
                                                                                at com.mobgen.halo.android.sample.App.onCreate(App.java:24)
                                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
                                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by jasta** [comment] 2016-05-02 18:46
This warning can be ignored and is the result of StrictMode's overly strict (*har har*) interpretation of disk I/O.  In this case, we're reading /proc/self/cmdline which is not disk I/O but is merely a kernel interface to read information it already has in memory.  If you're interested, you could submit a patch to make the error disappear by just adding a temporary strict mode call to allow disk I/O in ProcessUtil.

Alternatively, we could possibly speed up the Stetho.initialize call by making the socket address determiniation (AddressNameHelper.createCustomAddress) happen lazily on the server thread instead of on the caller thread as it is now.  This solution is likely preferred and can be done with a simple API change:

  serverManager = new ServerManager(new LocalSocketServerFactory() {
    LocalSocketServer newInstance() {
     // existing new here...
    }
  });

**Comment by jasta** [comment] 2016-05-02 18:46
Closing as this is harmless to ignore.

**Closed by jasta** 2016-05-02 18:46 UTC

**Comment by deviant-studio** [comment] 2016-11-17 11:05
You should fix this guys. Please follow platform guidelines even if the issue is not harmful.

**Comment by hzsweers** [comment] 2017-11-25 01:51
@jasta would you be open to a PR using your demoed approach?
