### ISSUE TITLE
Irreproducible NPE during onPossiblyChanged

### ISSUE THREAD

**Issue by TWiStErRob** [facebook/stetho#375] opened 2016-04-18 10:25 UTC
I got a crash which I couldn't reproduce, sorry. I still thought it might be helpful to report it.

I did the following in my app (as far as I remember):
- [laptop/phone] run the app from IDEA (main activity)
- [phone] open an activity linked from main
- [laptop] inspect its UI in Chrome
- [laptop] back to IDEA (Developer Tools left open)
- [phone] back button -> main activity
- [phone] open navigation drawer -> crash:

```
java.lang.NullPointerException
    at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
    at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
    at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
    at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
    at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
    at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
    at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5356)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)
```

Looking at the code:

``` java
/*387*/ if (newElementInfo.parentElement != oldElementInfo.parentElement) {
/*388*/     int parentNodeId = mObjectIdMapper.getIdForObject(oldElementInfo.parentElement);
/*389*/     int nodeId = mObjectIdMapper.getIdForObject(element);
/*390*/     mUpdateListeners.onChildNodeRemoved(parentNodeId, nodeId);
/*391*/ }
```

`oldElementInfo` cannot be null, because then the `if` would've thrown.
`mObjectIdMapper` is initialized in the constructor and is final, so cannot be null
Short WTF, then realized:

``` java
public @Nullable Integer getIdForObject(Object object);
```

So that leaves the hidden unboxing as the culprit: it is declared as nullable, but not checked for null. I guess it was assumed that it always exists?

**Comment by nicholasrout** [comment] 2016-04-18 14:09
I got the exact same crash now, with a similar process: run app from Android Studio -> Open Chrome Inspect -> Rotate device to landscape (triggering onCreate) -> Crash (same NPE as above)

**Comment by jasta** [comment] 2016-06-02 03:57
Hmm.  @rickbrew any thoughts here?

**Comment by frannois** [comment] 2016-08-10 20:18
looks like duplicate of  https://github.com/facebook/stetho/issues/381 ?

**Comment by TWiStErRob** [comment] 2016-08-10 20:31
Here, it's weird that this is an older issue and this is the duplicate, but that's just bookkeeping. I think that contains more info so this can be duped into that one.

@rickbrew is assigned to both, but didn't comment on either... @jasta what's up with that?

**Comment by frannois** [comment] 2016-08-10 20:41
Oh, I didn't tag any of the two as a duplicate of the other one officially. They are just duplicates of one another. I leave the bookkeeping to the bookkeeper :)

**Comment by ggunders** [comment] 2016-08-16 04:56
this consistently happens during all stages of my app. if Chrome inspect is up this will crash here
com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)

will have to disable stetho until this bug is fixed

**Comment by TWiStErRob** [comment] 2016-08-16 07:41
@ggunders can you please try to create a stripped down version of your app (minimal code and layout) where you can still repro the issue? They don't have a consistent repro (one that crashes every time), so it's near impossible to fix. You're the first to claim to have this consistently, and if you just passive-agressively ignore it, that info is lost with you.

**Comment by rickbrew** [comment] 2016-11-21 21:47
Duplicate of #381

**Closed by rickbrew** 2016-11-21 21:47 UTC
Labels: duplicate
