### ISSUE TITLE
NullPointerException while using it

### ISSUE THREAD

**Issue by ajaykumarmeher** [facebook/stetho#369] opened 2016-04-09 16:41 UTC
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:160)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:141)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:127)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.Observable$2.call(Observable.java:233)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.Observable$2.call(Observable.java:225)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8644)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-09 22:08:18.832 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-09 22:08:18.833 11147-11147/com.samalaitech.ultrastocksservicerevamp W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by jasta** [comment] 2016-04-13 18:57
This occurs when you add StethoInterceptor as a regular interceptor instead of a network interceptor.  Check the API carefully.  Duplicate of #267

**Closed by jasta** 2016-04-13 18:57 UTC
