### ISSUE TITLE
inspect no data ,and the log show this.why?

### ISSUE THREAD

**Issue by HywTony** [facebook/stetho#74] opened 2015-02-25 06:49 UTC
![image](https://cloud.githubusercontent.com/assets/6284844/6366222/5f58e36e-bcfd-11e4-8fb1-31851acedc64.png)

**Comment by jasta** [comment] 2015-02-26 20:27
Duplicate of #49, which is fixed in master.  A new release is expected this week to address the issue.

Note however, that this is a harmless error and shows up even in the sample app.

**Closed by jasta** 2015-02-26 20:27 UTC
