### ISSUE TITLE
AbstractMethodError in LocalSocketHttpServer$WorkerThread

### ISSUE THREAD

**Issue by nm2n** [facebook/stetho#321] opened 2015-12-23 10:18 UTC
I'm trying to integrate Stetho in my existing project. At startup I'm getting following error:

```
12-23 11:06:38.853 18894-19192/com.package.name E/AndroidRuntime: FATAL EXCEPTION: StethoWorker2
                                                                     Process: com.package.name, PID: 18894
                                                                     java.lang.AbstractMethodError: abstract method "void org.apache.http.HttpConnection.close()"
                                                                         at com.facebook.stetho.server.LocalSocketHttpServer$WorkerThread.run(LocalSocketHttpServer.java:243)
```

I initialize Stetho in the applications onCreate() method:

```java
public class MyApplication extends Application {
  public void onCreate() {
    super.onCreate();
    Stetho.initializeWithDefaults(this);
  }
}
```

Any idea what could cause this issue?

**Comment by jasta** [comment] 2015-12-23 20:31
This is caused by #288 which was fixed in the latest master, but not yet released.  There is a work-around here: https://github.com/facebook/stetho/issues/251#issuecomment-132354339, though the work-around has some issues too (greatly increases your APK size).  If you want to try the 1.2.1-SNAPSHOT release, you can checkout the source from the github page and run ./gradlew installArchives.  This will add the 1.2.1-SNAPSHOT release to your local machine where gradle can resolve it or you can manually add the jar files to your project.

All that said, we will likely be cutting a new release shortly after the holidays so you could just use the work-around until then.

**Closed by jasta** 2015-12-23 20:31 UTC
Labels: bug, duplicate
