### ISSUE TITLE
OkHttp StethoInterceptor fails with "unexpected end of stream" when uploading "multipart" data

### ISSUE THREAD

**Issue by kboyarshinov** [facebook/stetho#220] opened 2015-07-10 06:54 UTC
Fails only on POST requests with "multipart/form-data" type.

Stacktrace:
```java
retrofit.RetrofitError: unexpected end of stream
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
            at retrofit.RxSupport$2.run(RxSupport.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ProtocolException: unexpected end of stream
            at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.close(HttpConnection.java:314)
            at okio.RealBufferedSink.close(RealBufferedSink.java:241)
            at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:899)
            at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:58)
            at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:879)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
            at com.squareup.okhttp.Call.getResponse(Call.java:274)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:227)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
            at com.squareup.okhttp.Call.execute(Call.java:81)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
            at retrofit.RxSupport$2.run(RxSupport.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)
```

Similar issue can be found in okhttp: https://github.com/square/okhttp/issues/1587 with problem and solution described.

As I see [`generateBody`](https://github.com/facebook/stetho/blob/master/stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java#L151) method contains error:
```java
    private byte[] generateBody() throws IOException {
      RequestBody body = mRequest.body();
      if (body == null) {
        return null;
      }
      Buffer buffer = new Buffer();
      body.writeTo(buffer);
      return buffer.readByteArray();
    }
```

**Comment by jasta** [comment] 2015-07-10 14:38
I'm not sure that issue applies here directly because we're not actually replacing the request body at all, we're just reading it.  In this case, it actually looks like Stetho's merely in the call stack of another, unrelated issue that is surfaced by the request body declared content length and actual length not matching.

You should take a look at what your request body's contentLength() method returns.  If it is not `-1` (as it is by default) then I suspect that's your problem.  If it is `-1`, then I'm curious what specific version of `okhttp` you are using because the code I have for okhttp 2.2.0 indicates clearly that only a positive contentLength() could cause this issue.

**Comment by jasta** [comment] 2015-07-10 14:39
If it really is somehow a Stetho specific issue, you can try commenting out our `generateBody()` method so that it doesn't read the body and see if it fixes it.  If it does, then I think we have found an `okhttp` bug, not a Stetho one :)

**Comment by kboyarshinov** [comment] 2015-07-10 15:46
@jasta Thank you. I'll check the things you mentioned and write results here. Maybe it is 'okhttp' bug but issue I pointed out tells it is improper use.

**Comment by jasta** [comment] 2015-07-10 18:06
Actually the issue you posted is referring to a different scenario that is
fixed by calling flush.  Our scenario is different and should be correct
usage.  In particular, they wrote to a forearding sink without calling
flush causing the final destination sink to be missing data.  In our case,
we don't forward but instead write to and read from our own direct buffer.
No flushing required and no impact on the original request body.

**Comment by jasta** [comment] 2015-07-13 21:21
Closing for now as I'm pretty certain the issue isn't within Stetho.  Re-open if you think I'm wrong :)

**Closed by jasta** 2015-07-13 21:21 UTC

**Comment by kboyarshinov** [comment] 2015-07-14 08:37
@jasta thank you anyway :)
